name: dbt Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-tests:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dbt
        run: pip install dbt-databricks
      - name: Run dbt deps
        run: dbt deps
        working-directory: ./dbt_project/migration_demo
      - name: Run tests (QA target)
        run: dbt build --target qa --profiles-dir .
        working-directory: ./dbt_project/migration_demo

  dbt-deploy-prod:
    needs: dbt-tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dbt
        run: pip install dbt-databricks
      - name: Deploy to Prod
        run: |
          dbt deps
          dbt run --target prod --profiles-dir .
        working-directory: ./dbt_project/migration_demo